### ISSUE TITLE
TODO Count 4/ FIXME Count 1

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-vue-organization-form#8]
- [ ] TODO: specify propsData
       Commit: (f0ae15d) Add core files.
       Fi[test/web/10-OrganizationForm.js:15](https://github.com/digitalbazaar/bedrock-vue-organization-form/blob/master/test/web/10-OrganizationForm.js#L15)
       Dave Longley commented a year ago

  - [ ] TODO: consider moving to `bedrock-karma`?
       Commit: (f0ae15d) Add core files.
       File:  [test/test.config.js:12](https://github.com/digitalbazaar/bedrock-vue-organization-form/blob/master/test/test.config.js#L12)
       Dave Longley commented a year ago

  - [ ] FIXME: make configurable
       Commit: (f0ae15d) Add core files.
       File:  [test/components/index.js:10](https://github.com/digitalbazaar/bedrock-vue-organization-form/blob/master/test/components/index.js#L10)
       Dave Longley commented a year ago

  - [ ] TODO: Move to bedrock-web-forms
       Commit: (e2993fc) Complete initial form component.
       File:  [BrOrganizationForm.vue:111](https://github.com/digitalbazaar/bedrock-vue-organization-form/blob/master/BrOrganizationForm.vue#L111)
       Ganesh Annan commented a year ago

  - [ ] TODO: $vm.el.something
       Commit: (f0ae15d) Add core files.
       Fi[test/web/10-OrganizationForm.js:19](https://github.com/digitalbazaar/bedrock-vue-organization-form/blob/master/test/web/10-OrganizationForm.js#L19)
       Dave Longley commented a year ago

       TODO Count          4
       FIXME Count         1
       Oldest Comment      a year ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: specify propsData
